[project]
name = 'koen-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.kusd-token]
path = 'contracts/kusd-token.clar'
clarity_version = 3
epoch = '3.2'

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.p2p-marketplace]
path = 'contracts/p2p-marketplace.clar'
clarity_version = 3
epoch = 'latest'

[contracts.reputation-sbt]
path = 'contracts/reputation-sbt.clar'
clarity_version = 3
epoch = '3.2'

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
