[project]
name = 'koen-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'

[[project.requirements]]
contract_id = 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token'

[contracts.kusd-token]
path = 'contracts/kusd-token.clar'
clarity_version = 3
epoch = '3.2'

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.p2p-marketplace]
path = 'contracts/p2p-marketplace.clar'
clarity_version = 3
epoch = '3.2'

[contracts.reputation-sbt]
path = 'contracts/reputation-sbt.clar'
clarity_version = 3
epoch = '3.2'

[contracts.reputation-sbt-v3]
path = 'contracts/reputation-sbt.clar'
clarity_version = 3
epoch = '3.2'

[contracts.p2p-marketplace-v3]
path = 'contracts/p2p-marketplace.clar'
clarity_version = 3
epoch = '3.2'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

[contracts.reputation-sbt-v4]
path = 'contracts/reputation-sbt.clar'
clarity_version = 3
epoch = '3.2'

[contracts.p2p-marketplace-v4]
path = 'contracts/p2p-marketplace.clar'
clarity_version = 3
epoch = '3.2'
