#!/bin/bash

# Kōen Protocol - Testnet Deployment Script
# This script helps deploy contracts to testnet using Leather wallet

echo "🚀 Kōen Protocol - Testnet Deployment"
echo "======================================"
echo ""
echo "This will deploy 4 contracts to Stacks testnet:"
echo "  1. kusd-token (kUSD stablecoin)"
echo "  2. oracle (Price feed)"
echo "  3. reputation-sbt (Reputation system)"
echo "  4. p2p-marketplace (Main contract)"
echo ""
echo "📝 IMPORTANT:"
echo "  - You need ~1 STX in your wallet for deployment fees"
echo "  - Each contract will open Leather for signature"
echo "  - Total cost: ~0.62 STX"
echo ""
echo "Your wallet address should be: SP7Q...KE6Y"
echo ""

read -p "Do you have testnet STX? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo ""
    echo "❌ You need testnet STX first!"
    echo ""
    echo "Get free testnet STX here:"
    echo "  👉 https://explorer.hiro.so/sandbox/faucet?chain=testnet"
    echo ""
    echo "Then run this script again."
    exit 1
fi

echo ""
echo "Great! Let's deploy..."
echo ""
echo "⚠️  NOTE: Clarinet deployments require private keys."
echo "   For security, we recommend deploying through the Stacks Explorer instead."
echo ""
echo "📖 MANUAL DEPLOYMENT STEPS:"
echo ""
echo "1. Go to: https://explorer.hiro.so/sandbox/deploy?chain=testnet"
echo ""
echo "2. Connect your Leather wallet"
echo ""
echo "3. Deploy each contract in this order:"
echo "   a) kusd-token.clar"
echo "   b) oracle.clar  "
echo "   c) reputation-sbt.clar"
echo "   d) p2p-marketplace.clar"
echo ""
echo "4. For each contract:"
echo "   - Copy the code from: ./contracts/[contract-name].clar"
echo "   - Paste into the explorer"
echo "   - Click 'Deploy'"
echo "   - Sign with Leather"
echo ""
echo "5. CRITICAL - Configure automatic reputation system:"
echo "   After deploying all contracts, you MUST call:"
echo "   reputation-sbt::set-marketplace(YOUR_MARKETPLACE_ADDRESS)"
echo "   This allows the marketplace to automatically manage reputation."
echo ""
echo "6. After deployment, update the contract addresses in:"
echo "   ../koen-frontend/lib/constants.ts"
echo ""
echo "Need the contract code? Run:"
echo "  cat contracts/kusd-token.clar"
echo "  cat contracts/oracle.clar"
echo "  cat contracts/reputation-sbt.clar"
echo "  cat contracts/p2p-marketplace.clar"
echo ""
